### ISSUE TITLE
deepgram.extra.to_SRT(response, line_length=1)

### ISSUE THREAD

**Issue by nuh0058** [deepgram/deepgram-python-captions#10]
i think it wold be a cool if you can implement (line_length) to yout code.
i use this official code deepgram.extra.to_SRT(response, line_length=1) , but i cant save to srt file

**Comment by SandraRodgers** [comment]
Thanks for that, this might be a bug because I thought line_length was implemented. I'll look into it this week!

**Comment by SandraRodgers** [comment]
I've added this implementation and released a new version of the package. Closing issue now.
