### ISSUE TITLE
Fails on empty transcription with IndexError: list index out of range

### ISSUE THREAD

**Issue by ddorian** [deepgram/deepgram-python-captions#15]
> What's happening that seems wrong?

It raises an IndexError.

## Steps to reproduce

```python

import deepgram_captions

mm = {
    "metadata": {
        "transaction_key": "deprecated",
        "request_id": "1ddf6fb2-703a-4d22-b4be-2d1c2eac1c02",
        "sha256": "c3595443b4c3b0950919e613f065983c5d5d8538ee2565ec985a990e8eef8d53",
        "created": "2024-07-03T10:15:54.608Z",
        "duration": 5.02,
        "channels": 1,
        "models": ["30089e05-99d1-4376-b32e-c263170674af"],
        "model_info": {
            "30089e05-99d1-4376-b32e-c263170674af": {
                "name": "2-general-nova",
                "version": "2024-01-09.29447",
                "arch": "nova-2",
            }
        },
    },
    "results": {
        "channels": [
            {
                "alternatives": [
                    {
                        "transcript": "",
                        "confidence": 0.0,
                        "words": [],
                        "paragraphs": {"transcript": "\n", "paragraphs": []},
                    }
                ],
                "detected_language": "en",
                "language_confidence": 0.15507619,
            }
        ]
    },
}

transcription = deepgram_captions.DeepgramConverter(mm)
print(transcription.response)
captions_text = deepgram_captions.webvtt(transcription)
```

```
Traceback (most recent call last):
  File "/home/mymymy.py", line 40, in <module>
    captions_text = deepgram_captions.webvtt(transcription)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.venv/lib/python3.12/site-packages/deepgram_captions/webvtt.py", line 25, in webvtt
    speaker_labels = "speaker" in lines[0][0]
                                  ~~~~~~~~^^^
IndexError: list index out of range
```

> To make it faster to diagnose the root problem. Tell us how can we reproduce the bug.

## Expected behavior

> What would you expect to happen when following the steps above?

To return empty captions

## Please tell us about your environment

> We want to make sure the problem isn't specific to your operating system or programming language.
  
- **Operating System/Version:** Ubuntu 22.04
- **Language:** Python 3.12

**Comment by VenoM9078** [comment]
Was this ever fixed? Facing the same issue more than often now.

**Comment by davidvonthenen** [comment]
hi @ddorian and @VenoM9078 

@ddorian it looks like you have no transcription in the results you have posted `"transcript": "",` so there is nothing there to caption. from the error there, you also need to enable `diarize`:
https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/listen/v1/rest/options.py#L64

@VenoM9078 you need to make sure that there `utterances` feature is enabled. if you are using the Python SDK, you need to enable this option:
https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/listen/v1/rest/options.py#L145C5-L145C15

**Comment by ddorian** [comment]
@dvonthenen it doesn't fail when there are transcripts and `diarize` is still false. So it's a bug of the code that fails to run when diarize is false.

**Comment by davidvonthenen** [comment]
Will take a look this morning.

**Comment by dvonthenen** [comment]
Finally, getting around to this... so you just want a check to throw an error if the transcription is empty? That shouldn't be a problem. In the future, you are also welcome to submit a PR to address the problem so it doesn't hold anything up.

**Comment by davidvonthenen** [comment]
Ahhh getting around to this... I missed the part about the `speaker` being missing. Will have a fix shortly.

**Comment by davidvonthenen** [comment]
PR is open:
https://github.com/deepgram/deepgram-python-captions/pull/18

**Comment by davidvonthenen** [comment]
PR has been merged!
