### ISSUE TITLE
Docs Incorrect & Don't Refer to this Repository

### ISSUE THREAD

**Issue by rawkode** [deepgram/deepgram-python-captions#17]
## What is the current behavior?

The docs for captioning refer to some non-existent API on the Python SDK.

https://developers.deepgram.com/docs/automatically-generating-webvtt-and-srt-captions

**Comment by davidvonthenen** [comment]
Hi @rawkode 

Thanks for pointing this out. I will update the link you have provided with the correct info. This repo is definitely the source for getting captions on python.

**Comment by davidvonthenen** [comment]
Hi @rawkode 

The documentation has been updated. If you run into any issues, reopen this issue or drop me a line in Discord.
